// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1TwXHXhLcy9x0-f81rT1robVF7QrlkwI',
    appId: '1:12898182951:web:1bcb88e8dbb83185916b02',
    messagingSenderId: '12898182951',
    projectId: 'medicalapp-1ddeb',
    authDomain: 'medicalapp-1ddeb.firebaseapp.com',
    storageBucket: 'medicalapp-1ddeb.appspot.com',
    measurementId: 'G-SQ9GPKPM3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA59iht9I2wj6u5TeP6uTlSgOa1jW8ixn8',
    appId: '1:12898182951:android:d536bc70f0dd325b916b02',
    messagingSenderId: '12898182951',
    projectId: 'medicalapp-1ddeb',
    storageBucket: 'medicalapp-1ddeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL9-pguPVRFGUyfsCqQmjKGmtROACrFcc',
    appId: '1:12898182951:ios:1e92c014ca6bd500916b02',
    messagingSenderId: '12898182951',
    projectId: 'medicalapp-1ddeb',
    storageBucket: 'medicalapp-1ddeb.appspot.com',
    iosClientId: '12898182951-ifagkv1giqbakj63q1s6038t827fl4ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL9-pguPVRFGUyfsCqQmjKGmtROACrFcc',
    appId: '1:12898182951:ios:1e92c014ca6bd500916b02',
    messagingSenderId: '12898182951',
    projectId: 'medicalapp-1ddeb',
    storageBucket: 'medicalapp-1ddeb.appspot.com',
    iosClientId: '12898182951-ifagkv1giqbakj63q1s6038t827fl4ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalapp',
  );
}
